title: "Deploy WordPress CMS on OCI compute instances using docker"
stackDescription: "Deploy containerized WordPress & MySQL on OCI using a single compute instance. "
schemaVersion: 1.2.0
version: "20201104"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: WordPress Configuration
  visible: true  
  variables:
    - admin_username
    - admin_password
    - wp_name
    - wp_schema
    - wp_password
    - show_advanced


- title: Instance Configuration
  visible: 
      and:
        - show_advanced
  variables:
    - compartment_ocid
    - node_shape
    - availability_domain_name 
    - public_ssh_key


- title: Network Configuration
  visible: 
      and:
        - show_advanced
  variables:
     - vcn
     - vcn_cidr

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: 
      and:
        - show_advanced
    title: "Compartment"
    description: "Compartment where your WordPress will be deployed."

  region:
    type: oci:identity:region:name
    required: true
    visible: 
      and:
        - show_advanced
    title: "Region"
    description: "Choose Region where your WordPress will be deployed."

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: 
      and:
        - show_advanced
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your WordPress and MDS will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  admin_password:
    type: password
    required: true
    title: "MySQL Admin User's Password"
    description: "Choose password for MySQL Database System admin user."
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  wp_password:
    type: password
    required: true
    title: "MDS WordPress User's Password"
    description: "Choose MySQL Password for WordPress User."
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  

  vcn:
    type: string
    visible: 
      and:
        - show_advanced
    required: true
    title: "VCN name"
    description: "Type VCN name where your WordPress and MDS will be deployed."

  vcn_cidr:
    type: string
    visible: 
      and:
        - show_advanced
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN CIDR for your WordPress and MDS deployments."

  node_shape:
    type: oci:core:instanceshape:name
    required: false
    visible: 
      and:
        - show_advanced
    title: "Wordpress node shape"
    description: "Choose Instance Shape for WordPress host."
    default: "VM.Standard2.1"
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_os:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS"
    description: "An Operating System that determines the operating system for WordPress host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for WordPress host."
    default: "7.8"
    enum:
      - "7.8"

  label_prefix:
    type: string
    required: false
    visible: false
    title: "WordPress Hostname Prefix"
    description: "Type WordPress Hostname Prefix."

  admin_username:
    type: string
    required: false
    title: "MySQL Admin Username"
    description: "Type MySQL Database Service's admin username."
    minLength: 1
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: 
      and:
        - show_advanced
  

  wp_name:
    type: string
    required: false
    title: "MySQL WordPress Username"
    description: "Type MySQL Username for WordPress."
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: 
      and:
        - show_advanced

  wp_schema:
    type: string
    required: false
    title: "MySQL WordPress Schema"
    description: "Type MySQL Schema/Database for WordPress."
    visible: 
      and:
        - show_advanced

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    description: "In order to access your private nodes with a public SSH key you will need to set up a bastion host (a.k.a. jump box). If using public nodes, bastion is not needed. Left blank to not import keys."
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: 
      and:
        - show_advanced


  
outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: copyableString
    visible: true
  wordpress_public_ip:
    title: "WordPress CMS Public IP"
    displayText: "WordPress CMS Public IP"
    type: string
    visible: true
